
#
#  Este servidor está definido como generic
#

# Dados para autenticação staff no furguard
FurGuard:
  ApiKey: ""
  ApiUrl: "https://api.nextfur.net/"

Messages:
  BannedItem: "§cOpa! Um item banido foi removido do seu inventário. §5[ x%amount% %item% ]"

# ;3
Config-Version: 1.0
Server-Role: "generic"